---
- name: "Static Website Installation"
  become: yes
  hosts: "worker1"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create default containers
      docker_container:
        name: "twitter-static-website"
        image: "jenkins:5000/groupe2/twitter-static-website:v5"
        state: started
        restart: "yes"
        ports: "80:80"
        env:
          PORT: "80"

...